### PR TITLE
Documentation improvements and follow modern conventions

### PR DESCRIPTION
**Pull request by neilb**
Hi Ovid,

I realise that this looks like "a whole bunch of stuff", but each change is quite small, and a lot of them are pod fixes or improvements, including all the outstanding RT tickets related to doc.

This is the first time I've done a PR on a branch, but I'm following Sawyer's guidelines for how to do a PR.

Any feedback on how you would have preferred this PR will be happily received.

Cheers,
Neil

### CODE REVIEW

**Comment by Ovid** [comment]
Neal, this looks great. I'll review this later. Sorry I haven't been responding during the holidays :) I'll get back to this later today.

**Comment by neilbowers** [comment]
A gentle nudge, to see if you want me to change anything in this PR?

**Comment by Ovid** [comment]
Thanks for this Neil. It looks great and is now merged :+1:

**Comment by neilb** [comment]
Awesome -- thanks!

**Pull request merged**
